name: Build and upload beta
on:
  push:
    branches:
      - dev

jobs:
  build_and_upload:
    name: Build & upload
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: maierj/fastlane-action@master
        name: Fastlane
        with:
          lane: 'beta'
        env:
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
